### ISSUE TITLE
add_beneficiary throws UserVaultDoesNotExist

### ISSUE THREAD

**Issue by ahoehn** [ioloapp/iolo#6]
Beim erstellen eines neuen Contacts (siehe Issue #5) wird ein UserVaultDoesNotExist Exception geworfen. Das macht keinen Sinn, weil ich als Contact jede valide IC-ID verwenden darf, egal ob der User bereits ein IOLO UserVault hat oder nicht.

**Comment by peterfust** [comment]
konnte ich nicht reproduzieren. Wenn ich einen neuen Internet Identity account erstelle aber KEINEN iolo account kann ich diesen principal als contact hinzufügen (aus einem weiteren iolo account heraus).
