### ISSUE TITLE
vetkey und keybox management in UI

### ISSUE THREAD

**Issue by ahoehn** [ioloapp/iolo#7]
Entweder muss das ganze vetkey encoding in das backend oder wir brauchen eine lösung für die stelle:

```
// Get vetkey for policies
const policyVetKey = await get_aes_256_gcm_key_for_policy(uiPolicy.id, (await this.getActor()));
```

Grund: da nun policy id vom backend gemacht wird, ist die undefined.

Error beim erstellen einer policy:
Error: Invalid record {encryption_public_key:vec nat8; policy_id:text} argument: field policy_id -> Invalid text argument: undefined at http://localhost:8080/index.js:5298:25 at http://localhost:8080/index.js:3991:29 at Array.map (<anonymous>) at zipWith (http://localhost:8080/index.js:3991:15) at Module.encode (http://localhost:8080/index.js:5293:75) at caller (http://localhost:8080/index.js:222:74) at CanisterActor.handler [as encrypted_symmetric_key_for_policies] (http://localhost:8080/index.js:255:34) at get_aes_256_gcm_key_for_policy (http://localhost:8080/index.js:107305:38) at IoloService.mapUiPolicyToPolicy (http://localhost:8080/index.js:107055:113) at async IoloService.addPolicy (http://localhost:8080/index.js:106690:24)

**Comment by peterfust** [comment]
ist gefixt, create_policy besteht nun aus zwei Operationen:
1. create_policy um eine id vom backend zu lösen
2. update_policy um die anderen attribute zu setzen
